# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Diego Andrade/Desktop/CPE133MazeGame/AMAZEingGame.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Diego Andrade/Desktop/CPE133MazeGame/AMAZEingGame.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Diego Andrade/Desktop/CPE133MazeGame/AMAZEingGame.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  {C:/Users/Diego Andrade/Desktop/CPE133MazeGame/AMAZEingGame.srcs/sources_1/imports/Downloads/Accumulator.sv}
  {C:/Users/Diego Andrade/Desktop/CPE133MazeGame/AMAZEingGame.srcs/sources_1/new/ClockDivider.sv}
  {C:/Users/Diego Andrade/Desktop/CPE133MazeGame/AMAZEingGame.srcs/sources_1/new/Maze1.sv}
  {C:/Users/Diego Andrade/Desktop/CPE133MazeGame/AMAZEingGame.srcs/sources_1/new/Maze1Drawer.sv}
  {C:/Users/Diego Andrade/Desktop/CPE133MazeGame/AMAZEingGame.srcs/sources_1/new/Maze1FSM.sv}
  {C:/Users/Diego Andrade/Desktop/CPE133MazeGame/AMAZEingGame.srcs/sources_1/imports/new/Mux2.sv}
  {C:/Users/Diego Andrade/Desktop/CPE133MazeGame/AMAZEingGame.srcs/sources_1/new/PlayerDrawer.sv}
  {C:/Users/Diego Andrade/Desktop/CPE133MazeGame/AMAZEingGame.srcs/sources_1/new/Timer.sv}
  {C:/Users/Diego Andrade/Desktop/CPE133MazeGame/AMAZEingGame.srcs/sources_1/new/ram8k_8_80x60.sv}
  {C:/Users/Diego Andrade/Desktop/CPE133MazeGame/AMAZEingGame.srcs/sources_1/new/univ_sseg.sv}
  {C:/Users/Diego Andrade/Desktop/CPE133MazeGame/AMAZEingGame.srcs/sources_1/new/vga_driver_80x60.sv}
  {C:/Users/Diego Andrade/Desktop/CPE133MazeGame/AMAZEingGame.srcs/sources_1/new/vga_fb__driver_80x60.sv}
  {C:/Users/Diego Andrade/Desktop/CPE133MazeGame/AMAZEingGame.srcs/sources_1/new/MazeTop.sv}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Diego Andrade/Desktop/CPE133MazeGame/AMAZEingGame.srcs/constrs_1/new/basys_3.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Diego Andrade/Desktop/CPE133MazeGame/AMAZEingGame.srcs/constrs_1/new/basys_3.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top MazeTop -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MazeTop.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MazeTop_utilization_synth.rpt -pb MazeTop_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
